
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NUM PA PF VIRGULA\n    Lista : PA Lista2\n    Lista2 : Conteudo PF\n           | PF\n    Conteudo : Elem VIRGULA Conteudo\n             | Elem\n    Elem : NUM\n         | Lista\n    '
    
_lr_action_items = {'PA':([0,2,10,],[2,2,2,]),'$end':([1,3,5,9,],[0,-1,-3,-2,]),'PF':([2,3,4,5,6,7,8,9,11,],[5,-1,9,-3,-5,-6,-7,-2,-4,]),'NUM':([2,10,],[7,7,]),'VIRGULA':([3,5,6,7,8,9,],[-1,-3,10,-6,-7,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Lista':([0,2,10,],[1,8,8,]),'Lista2':([2,],[3,]),'Conteudo':([2,10,],[4,11,]),'Elem':([2,10,],[6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Lista","S'",1,None,None,None),
  ('Lista -> PA Lista2','Lista',2,'p_gramatica','listas_sin.py',6),
  ('Lista2 -> Conteudo PF','Lista2',2,'p_gramatica','listas_sin.py',7),
  ('Lista2 -> PF','Lista2',1,'p_gramatica','listas_sin.py',8),
  ('Conteudo -> Elem VIRGULA Conteudo','Conteudo',3,'p_gramatica','listas_sin.py',9),
  ('Conteudo -> Elem','Conteudo',1,'p_gramatica','listas_sin.py',10),
  ('Elem -> NUM','Elem',1,'p_gramatica','listas_sin.py',11),
  ('Elem -> Lista','Elem',1,'p_gramatica','listas_sin.py',12),
]
